[project]
name = "fuse-usa-brown-kendrick"
version = "0.1.0"
description = "Data Fusion from M.G. Brown & J.W. Kendrick Sources."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "pyyaml>=6.0.3",
]
